// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI agent that analyzes an image and provides a rationale for its decision on whether the image is AI-generated.
 *
 * - analyzeImage - A function that handles the image analysis process.
 * - AnalyzeImageInput - The input type for the analyzeImage function.
 * - AnalyzeImageOutput - The return type for the analyzeImage function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeImageInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo to be analyzed, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type AnalyzeImageInput = z.infer<typeof AnalyzeImageInputSchema>;

const AnalyzeImageOutputSchema = z.object({
  isAiGenerated: z.boolean().describe('Whether or not the image is AI-generated.'),
  confidenceScore: z.number().describe('The confidence score (0-1) of the AI`s decision.'),
  rationale: z.string().describe('The rationale for the AI`s decision.'),
});
export type AnalyzeImageOutput = z.infer<typeof AnalyzeImageOutputSchema>;

export async function analyzeImage(input: AnalyzeImageInput): Promise<AnalyzeImageOutput> {
  return analyzeImageFlow(input);
}

const analyzeImagePrompt = ai.definePrompt({
  name: 'analyzeImagePrompt',
  input: {schema: AnalyzeImageInputSchema},
  output: {schema: AnalyzeImageOutputSchema},
  prompt: `You are a skeptical and meticulous AI image analyst. Your primary goal is to distinguish between genuine photographs and AI-generated images, with a strong bias against making false accusations. Only classify an image as AI-generated if you find clear and undeniable evidence.

Look for specific artifacts commonly associated with AI generation, such as:
- Illogical or inconsistent lighting and shadows.
- Unnatural or distorted features on people and animals (e.g., hands, eyes, ears).
- Strange, nonsensical, or garbled text within the image.
- Unnatural textures, patterns, or repeating elements.
- Warped or distorted backgrounds.
- An overall "too perfect" or plastic-like appearance.

Analyze the following image. If no such artifacts are present, you should classify it as authentic. Provide your analysis as a JSON string that conforms to the schema.

Image: {{media url=photoDataUri}}`,
});

const analyzeImageFlow = ai.defineFlow(
  {
    name: 'analyzeImageFlow',
    inputSchema: AnalyzeImageInputSchema,
    outputSchema: AnalyzeImageOutputSchema,
  },
  async input => {
    const {output} = await analyzeImagePrompt(input);
    return output!;
  }
);
